// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Infrastructure.Contexts;

#nullable disable

namespace WebApi.Migrations;

[DbContext(typeof(UniversityWriteDbContext))]
partial class UniversityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.1")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("WebApi.Domain.Entities.Course", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<int>("Credits")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.HasKey("Id");

                b.ToTable("Courses", (string)null);
            });

        modelBuilder.Entity("WebApi.Domain.Entities.CourseAssignment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<DateTime>("AssignedAt")
                    .HasColumnType("datetime(6)");

                b.Property<Guid>("CourseId")
                    .HasColumnType("char(36)");

                b.Property<Guid>("TeacherId")
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.HasIndex("CourseId");

                b.HasIndex("TeacherId", "CourseId")
                    .IsUnique();

                b.ToTable("CourseAssignments", (string)null);
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Enrollment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.Property<Guid>("CourseAssignmentId")
                    .HasColumnType("char(36)");

                b.Property<DateTime>("EnrolledAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<Guid>("StudentId")
                    .HasColumnType("char(36)");

                b.Property<DateTime?>("WithdrawnAt")
                    .HasColumnType("datetime(6)");

                b.HasKey("Id");

                b.HasIndex("CourseAssignmentId");

                b.HasIndex("StudentId", "CourseAssignmentId")
                    .IsUnique();

                b.ToTable("Enrollments", (string)null);
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Student", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.ToTable("Students", (string)null);
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Teacher", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("char(36)");

                b.HasKey("Id");

                b.ToTable("Teachers", (string)null);
            });

        modelBuilder.Entity("WebApi.Domain.Entities.CourseAssignment", b =>
            {
                b.HasOne("WebApi.Domain.Entities.Course", "Course")
                    .WithMany("Assignments")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_CourseAssignments_Courses");

                b.HasOne("WebApi.Domain.Entities.Teacher", "Teacher")
                    .WithMany("CourseAssignments")
                    .HasForeignKey("TeacherId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_CourseAssignments_Teachers");

                b.Navigation("Course");

                b.Navigation("Teacher");
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Enrollment", b =>
            {
                b.HasOne("WebApi.Domain.Entities.CourseAssignment", "CourseAssignment")
                    .WithMany("Enrollments")
                    .HasForeignKey("CourseAssignmentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Enrollments_CourseAssignments");

                b.HasOne("WebApi.Domain.Entities.Student", "Student")
                    .WithMany("Enrollments")
                    .HasForeignKey("StudentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_Enrollments_Students");

                b.Navigation("CourseAssignment");

                b.Navigation("Student");
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Student", b =>
            {
                b.OwnsOne("WebApi.Domain.ValueObjects.Email", "Email", b1 =>
                    {
                        b1.Property<Guid>("StudentId")
                            .HasColumnType("char(36)");

                        b1.Property<string>("Address")
                            .IsRequired()
                            .HasMaxLength(255)
                            .HasColumnType("varchar(255)")
                            .HasColumnName("Email");

                        b1.HasKey("StudentId");

                        b1.ToTable("Students");

                        b1.WithOwner()
                            .HasForeignKey("StudentId");
                    });

                b.OwnsOne("WebApi.Domain.ValueObjects.FullName", "Name", b1 =>
                    {
                        b1.Property<Guid>("StudentId")
                            .HasColumnType("char(36)");

                        b1.Property<string>("FirstName")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("FirstName");

                        b1.Property<string>("FirstSurname")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("FirstSurname");

                        b1.Property<string>("MiddleName")
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("MiddleName");

                        b1.Property<string>("SecondSurname")
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("SecondSurname");

                        b1.HasKey("StudentId");

                        b1.ToTable("Students");

                        b1.WithOwner()
                            .HasForeignKey("StudentId");
                    });

                b.Navigation("Email")
                    .IsRequired();

                b.Navigation("Name")
                    .IsRequired();
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Teacher", b =>
            {
                b.OwnsOne("WebApi.Domain.ValueObjects.Email", "Email", b1 =>
                    {
                        b1.Property<Guid>("TeacherId")
                            .HasColumnType("char(36)");

                        b1.Property<string>("Address")
                            .IsRequired()
                            .HasMaxLength(255)
                            .HasColumnType("varchar(255)")
                            .HasColumnName("Email");

                        b1.HasKey("TeacherId");

                        b1.ToTable("Teachers");

                        b1.WithOwner()
                            .HasForeignKey("TeacherId");
                    });

                b.OwnsOne("WebApi.Domain.ValueObjects.FullName", "Name", b1 =>
                    {
                        b1.Property<Guid>("TeacherId")
                            .HasColumnType("char(36)");

                        b1.Property<string>("FirstName")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("FirstName");

                        b1.Property<string>("FirstSurname")
                            .IsRequired()
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("FirstSurname");

                        b1.Property<string>("MiddleName")
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("MiddleName");

                        b1.Property<string>("SecondSurname")
                            .HasMaxLength(100)
                            .HasColumnType("varchar(100)")
                            .HasColumnName("SecondSurname");

                        b1.HasKey("TeacherId");

                        b1.ToTable("Teachers");

                        b1.WithOwner()
                            .HasForeignKey("TeacherId");
                    });

                b.Navigation("Email")
                    .IsRequired();

                b.Navigation("Name")
                    .IsRequired();
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Course", b =>
            {
                b.Navigation("Assignments");
            });

        modelBuilder.Entity("WebApi.Domain.Entities.CourseAssignment", b =>
            {
                b.Navigation("Enrollments");
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Student", b =>
            {
                b.Navigation("Enrollments");
            });

        modelBuilder.Entity("WebApi.Domain.Entities.Teacher", b =>
            {
                b.Navigation("CourseAssignments");
            });
#pragma warning restore 612, 618
    }
}
